FROM gradle:8.11.1-jdk21-graal AS builder
WORKDIR /usr/app/
COPY . .
RUN /usr/bin/gradle clean quarkusBuild -Dquarkus.package.jar.enabled=false -Dquarkus.native.enabled=true --no-daemon 

FROM ubuntu:jammy
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --from=builder --chown=1001:root /usr/app/build/*-runner /work/application

EXPOSE 8080
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
