name: Docker Image Build
on:
  push:
    branches: [ "deploy" ]

env:
  REGISTRY: europe-west10-docker.pkg.dev/finveloxrepo/image-repo
  IMAGE_NAME: nginx

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      actions: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get tag
      id: get-tag
      run: echo "full_tag=${{ env.IMAGE_NAME }}:1.25" >> "$GITHUB_OUTPUT"
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4
      with:
         version: 'latest'
      id: install
    - name: Set kube context
      uses: azure/k8s-set-context@v4
      with:
         method: kubeconfig
         kubeconfig: ${{ secrets.PERGAMON_K8S_CONFIG }}
    - name: Deploy to k8s
      uses: Azure/k8s-deploy@v5
      with:
         namespace: 'pergamon'
         manifests: |
            k8s
         images: ${{ steps.get-tag.outputs.full_tag }}

